pionback/mainapp/urls.py
from django.urls import path

from .views import BaseView, NawsView, NewsDetailView, SubscriptionView, UnSubscriptionView, InfoView

urlpatterns = [
 path('', BaseView.as_view(), name="base"),
 path('news/', NawsView.as_view(), name="news"),

 path('news/<str:slug>/', NawsView.as_view(), name="news"),
 path('subscription/', SubscriptionView.as_view(), name="subscription"),
 path('unsubscription/', UnSubscriptionView.as_view(), name="unsubscription"),

 path('info_form/', InfoView.as_view(), name="info_form"),


 path('news/item/<str:slug>/', NewsDetailView.as_view(), name="news")
]

pionback/pionback/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from public import views
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

#router.register(r'user_pass', views.NewPass)

router.register(r'user-requests', views.UserRequestViewSet)
router.register(r'targets', views.TargetViewSet)
router.register(r'practices', views.PracticeViewSet)
router.register(r'outcomes', views.OutcomeViewSet)
router.register(r'outcome-names', views.OutcomeExactNameViewSet)
router.register(r'outcome-indicators', views.OutcomeIndicatorViewSet)
router.register(r'outcome-methods', views.OutcomeMethodViewSet)
router.register(r'logical-models', views.LogicalModelViewSet)
router.register(r'logical-model-change-requests', views.LogicalModelChangeRequestViewSet)
router.register(r'programs', views.ProgramViewSet)
router.register(r'assumptions', views.AssumptionViewSet)
router.register(r'contexts', views.ContextViewSet)
router.register(r'activities', views.ActivityViewSet)
router.register(r'target-descriptions', views.TargetDescriptionViewSet)
router.register(r'program-outputs', views.ProgramOutputViewSet)
router.register(r'program-short-outcomes', views.ProgramShortOutcomeViewSet)
router.register(r'program-mid-outcomes', views.ProgramMidOutcomeViewSet)
router.register(r'program-impacts', views.ProgramImpactViewSet)

router.register(r'mpl-outputs', views.MonitoringPlanLineOutputViewSet)
router.register(r'mpl-short-outcomes', views.MonitoringPlanLineShortOutcomeViewSet)
router.register(r'mpl-mid-outcomes', views.MonitoringPlanLineMidOutcomeViewSet)
router.register(r'mpl-impacts', views.MonitoringPlanLineImpactViewSet)

router.register(r'mfl-outputs', views.MonitoringFormLineOutputViewSet)
router.register(r'mfl-short-outcomes', views.MonitoringFormLineShortOutcomeViewSet)
router.register(r'mfl-mid-outcomes', views.MonitoringFormLineMidOutcomeViewSet)
router.register(r'mfl-impacts', views.MonitoringFormLineImpactViewSet)

#Загрузка разделов
router.register(r'thematic-groups', views.ThematicGroupViewSet)
router.register(r'methods', views.MethodViewSet)
router.register(r'tool-tags', views.ToolTagViewSet)
router.register(r'outcome-levels', views.OutcomeLevelViewSet)
router.register(r'monitoring-elements', views.MonitoringElementViewSet)
router.register(r'organization-activities', views.OrganizationActivityViewSet)

#Библиотека инструментов
router.register(r'tools', views.ToolViewSet)
router.register(r'tool-change-requests', views.ToolChangeRequestViewSet)

#Библиотека кейсов
router.register(r'cases', views.CaseViewSet)
router.register(r'case-change-requests', views.CaseChangeRequestViewSet)
router.register(r'evaluation-reports', views.EvaluationReportViewSet)
router.register(r'evaluation-report-change-requests', views.EvaluationReportChangeRequestViewSet)



#Представления данных в отчете
router.register(r'representation-methods', views.RepresentationMethodViewSet)

#Вид оценки
router.register(r'evaluation-types', views.EvaluationTypeViewSet)

#Метод анализа
router.register(r'analysis-methods', views.AnalysisMethodViewSet)


urlpatterns = [

    path('api/send-new-user-password/', views.SendNewUserPassword, name="user_pass"),


    path('api/testItem/', views.TestItem, name="testItem"),



    path('api/', include(router.urls)),
    path('api/o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/mainapp/', include('mainapp.urls')),
    path('api/admin/', admin.site.urls),
    path('api/download', views.download),
    path('api/download-plan', views.downloadPlan),
    path('api/download-form', views.downloadForm),
    url('^.*', TemplateView.as_view(template_name="index.html")),
]

pionback/mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db.models import Q
from django.utils import timezone
from django.urls import reverse

User = get_user_model()

class newsManager:
    @staticmethod
    def category_list(*args, **kwargs):
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')
            products.extend(model_products)

        return products

class newsitemlist:
    objects = newsManager()


class MainForm(models.Model):
    class Meta():
        db_table = 'user_mail'
        verbose_name = "Форма обратной связи"
        verbose_name_plural = "Форма обратной связи"

    fname = models.CharField(max_length=255, verbose_name='Имя')
    lname = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=15, verbose_name='Телефон')
    mail = models.EmailField(verbose_name='Mail')
    msg = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return self.mail

class Subscription(models.Model):
    class Meta():
        db_table = 'mail_list'
        verbose_name = "Подписки"
        verbose_name_plural = "Подписки"

    mail = models.EmailField(verbose_name='Mail')

    def __str__(self):
        return self.mail

class NewsCat(models.Model):
    class Meta():
        db_table = 'naws_cat'
        verbose_name = "Разделы новостей"
        verbose_name_plural = "Разделы новостей"
        ordering = ["create"]


    STATUS_NORMAL = 'normal'
    STATUS_BIG = 'big'
    STATUS_OVER_BIG = 'over_big'

    STATUS_CHOICES = (
        (STATUS_NORMAL, 'Нормальный'),
        (STATUS_BIG, 'Большой'),
        (STATUS_OVER_BIG, 'Очень большой'),
    )

    size = models.CharField(max_length=255, default=STATUS_NORMAL, choices=STATUS_CHOICES, verbose_name='Шрифт')

    name = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(unique=True)
    create = models.DateTimeField("Дата создания", auto_now_add=True)

    def __str__(self):
        return self.name

class News(models.Model):
    class Meta():
        db_table = 'naws'
        verbose_name = "Новости"
        verbose_name_plural = "Новости"
        ordering = ["create"]

    category = models.ForeignKey(NewsCat, verbose_name='Категория', on_delete=models.CASCADE)
    create = models.DateTimeField("Дата создания", auto_now_add=True)
    name = models.CharField(max_length=255, verbose_name='Название новости')
    title = models.CharField(max_length=255, verbose_name='title в браузере')
    desc = models.CharField(max_length=255, verbose_name='desc в браузере')
    slug = models.SlugField(unique=True)

    image = models.ImageField(verbose_name='Изображение')

    minitext = models.TextField(verbose_name='Краткое описание', null=True)
    maintext = models.TextField(verbose_name='Описание', null=True)

    active = models.BooleanField("Активно", default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return get_news_url(self, 'news_detail')

pionback/mainapp/forms.py
from django.forms import ModelForm
from .models import Subscription, MainForm

class SubscriptionForms(ModelForm):
	class Meta:
		model = Subscription
		fields = '__all__'

class MainFormForms(ModelForm):
	class Meta:
		model = MainForm
		fields = '__all__'

pionback/mainapp/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.views.generic import ListView, View
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.http import is_safe_url, urlunquote
from django.db.models import Q

from datetime import datetime, timedelta

from django.contrib import messages

from .models import News, newsitemlist, Subscription
from .forms import SubscriptionForms, MainFormForms

class UnSubscriptionView(View):
    def get(self, request, *args, **kwargs):
        if request.GET.get('mail'):
            created = Subscription.objects.get(
                mail=request.GET.get('mail')
            )
            messages.add_message(request, messages.INFO, 'Подписка отменена')
            created.delete()

        return HttpResponseRedirect('/')

class InfoView(View):
    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = MainFormForms(request.POST, request.FILES or None)
        if request.method == "POST" and form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Сообщение отправлено')


        next = request.META.get('HTTP_REFERER')
        if next:
            next = urlunquote(next)  # HTTP_REFERER may be encoded.
        return HttpResponseRedirect(next)


class SubscriptionView(View):
    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = SubscriptionForms(request.POST, request.FILES or None)
        if request.method == "POST" and form.is_valid():

            created = Subscription.objects.get_or_create(
                mail=form.cleaned_data['mail']
            )
            if created:
                messages.add_message(request, messages.INFO, 'Вы успешно подписаны')
            else:
                messages.add_message(request, messages.INFO, 'Вы уже подписаны')


        else:
            print(form.errors)

        next = request.META.get('HTTP_REFERER')
        if next:
            next = urlunquote(next)  # HTTP_REFERER may be encoded.

        return HttpResponseRedirect(next)

class BaseView(View):
    def get(self, request, *args, **kwargs):
        mainForm = MainFormForms()
        form = SubscriptionForms()

        if request.GET.get('main_form'):
            search_name = request.GET.get('main_form')

        return render(request, 'base.html', {'formSub': form, 'mainForm': mainForm, 'main_form':True})

class NawsView(ListView):
    def dispatch(self, request, *args, **kwargs):

        catlist = newsitemlist.objects.category_list('newscat')
        self.model = News
        form = SubscriptionForms()

        search_name = ''
        search_date = ''

        if request.GET.get('search_name'):
            search_name = request.GET.get('search_name')

        if request.GET.get('month'):
            search_date = request.GET.get('month')


        if 'slug' in kwargs:
            if request.GET.get('month'):
                self.queryset = self.model._base_manager.filter(Q(category__slug=kwargs['slug'])&Q(name__icontains=search_name)&Q(create__month=search_date))
            else:
                self.queryset = self.model._base_manager.filter(Q(category__slug=kwargs['slug'])&Q(name__icontains=search_name))

            self.extra_context = {'catlist': catlist, 'search_name':search_name, 'razItem': kwargs['slug'], 'formSub': form}
        else:
            if request.GET.get('month'):
                self.queryset = self.model._base_manager.filter(Q(name__icontains=search_name)&Q(name__icontains=search_name)&Q(create__month=search_date))
            else:
                self.queryset = self.model._base_manager.filter(Q(name__icontains=search_name)&Q(name__icontains=search_name))

            self.extra_context = {'catlist': catlist, 'search_name':search_name, 'formSub': form}

        self.paginate_by = 4
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'news'
    template_name = 'news.html'
    slug_url_kwarg = 'slug'


class NewsDetailView(DetailView):

    def dispatch(self, request, *args, **kwargs):
        catlist = newsitemlist.objects.category_list('newscat')
        self.model = News
        form = SubscriptionForms()

        self.queryset = self.model._base_manager.all()
        self.extra_context = {'catlist': catlist, 'formSub': form}
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'news_detail'
    template_name = 'details_news.html'
    slug_url_kwarg = 'slug'

pionback/mainapp/templates/details_news.html
{% extends 'base.html' %}

{% block content %}



<div style="display: none;">
{% block title %}{{ news_detail.title }}{% endblock %}
{% block description %}{{ news_detail.desc }}{% endblock %}
</div>


<section class="news">
        <div class="news_top">
            <div class="container">
                <div class="news_top-title">
                    Новости ПИОН
                </div>
            </div>
        </div>

        <div class="container">
            <div class="news_body">
                <div class="aside_burger">
                    <span></span>
                </div>
                <div class="news_wrapper">

					<div class="gender-area frame" style=" max-width: 100%;">

						<p class="breadcrumbs">
							<a href="/">Главная</a> / <a href="/news/">Новости</a> / <a href="#">{{ news_detail.name }}</a>
						</p>

						<div class="det_text">
							<h1>{{ news_detail.name }}</h1>

							<img class="news_detailImg" src="{{MEDIA_URL}}{{news_detail.image.url}}/" alt="">

							<div>
								{{ news_detail.maintext|safe }}
							</div>

						</div>

					</div>



                </div>
                <div class="news_aside">
                    {% include 'right_block.html'  %}
                </div>
            </div>
        </div>

    </section>



{% endblock content %}

pionback/mainapp/templates/news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="news">
        <div class="news_top">
            <div class="container">
                <div class="news_top-title">
                    Новости ПИОН
                </div>
            </div>
        </div>

        <div class="container">
            <div class="news_body">
                <div class="aside_burger">
                    <span></span>
                </div>
                <div class="news_wrapper">

                    {% for new in news %}
                         <div class="news_item">
                            <div class="news_item-img" style="background: url({{new.image.url}})">

                            </div>
                            <div class="news_item-info">
                                <div class="news_item-title">
                                    {{ new.name }}
                                </div>
                                <div class="news_item-date">
                                    {{ new.create|date:"d.m.Y" }}
                                </div>
                                <div class="news_item-text">
                                    {{ new.minitext|safe }}
                                </div>
                                <a href="/news/item/{{ new.slug }}" class="news_item-btn">ПОДРОБНЕЕ</a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="news_aside">
                    {% include 'right_block.html'  %}

                </div>
            </div>
        </div>



<div class = "pagination">
    {% if page_obj.number != 1 %}
        <a href="?page=1" class="arrow">&laquo;</a>
    {% endif %}

	{% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="arrow">‹</a>
    {% endif %}

	{% for pages in page_obj.paginator.page_range %}
		{% if page_obj.number == pages %}
			<a href=""><strong>{{ pages }}</strong></a>
		{% elif pages > page_obj.number|add:'-3' and pages < page_obj.number|add:'3' %}
			<a href="?page={{ pages }}">
				<span>{{ pages }}</span>
			</a>
		{% endif %}
	{% endfor %}

	{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}" class="arrow">›</a>
    {% endif %}

    {% if page_obj.number != page_obj.paginator.num_pages %}
        <a href="?page={{ page_obj.paginator.num_pages }}" class="arrow">»</a>
    {% endif %}
</div>


        </div>
    </section>


    <section class="bottom_menu">
        <div class="bottom_menu-wrapper">
            <a href="#" class="bottom_menu-link">О нас</a>
            <div class="bottom_menu-link">Наши продукты
                <div class="bottom_menu-body">
                    <a href="#" class="bottom_menu-item">
                        Методическое пособие по применению Теории измерений при планировании программы
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Методика построения системы измерения и оценки социальных результатов
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Рекомендации по оценке социально-экономической эффектиности социальных программ
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Стандарт доказательности
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Методика сбора и анализа обратной связи
                    </a>
                </div>
            </div>
            <div class="bottom_menu-link">наши Услуги
                <div class="bottom_menu-body">
                    <a href="#" class="bottom_menu-item">
                        Проектирование и корректировка систем измерения и оценки результатов
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Разработка Теории изменений
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Оценка программ
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Проведение тренингов и косультирование
                    </a>
                    <a href="#" class="bottom_menu-item">
                        Анализ релевантного международного опыта
                    </a>
                </div>
            </div>
            <div class="bottom_menu-link">Наши ресурсы
                <div class="bottom_menu-body">
                    <a href="https://socialvalue.ru" class="bottom_menu-item">
                        База знаний по оценке
                    </a>
                    <a href="https://pion.org.ru" class="bottom_menu-item">
                        IT-сервис ПИОН
                    </a>
                    <a href="https://base.socialvalue.ru" class="bottom_menu-item">
                        Слушай с пользой!
                    </a>
                </div>
            </div>
        </div>
    </section>


{% endblock content %}

pionback/mainapp/templates/right_block.html
{% load static %}

<div class="news_messanges">
    <div class="news_messanges-title">
        Оставайтесь на связи
    </div>
    <div class="news_messanges-wrapper">
        <a href="#" class="news_messanges-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24">
                <path
                        d="M7 11v2.4h3.97c-.16 1.029-1.2 3.02-3.97 3.02-2.39 0-4.34-1.979-4.34-4.42 0-2.44 1.95-4.42 4.34-4.42 1.36 0 2.27.58 2.79 1.08l1.9-1.83c-1.22-1.14-2.8-1.83-4.69-1.83-3.87 0-7 3.13-7 7s3.13 7 7 7c4.04 0 6.721-2.84 6.721-6.84 0-.46-.051-.81-.111-1.16h-6.61zm0 0 17 2h-3v3h-2v-3h-3v-2h3v-3h2v3h3v2z"
                        fill-rule="evenodd" clip-rule="evenodd" />
            </svg>
        </a>
        <a href="#" class="news_messanges-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path
                        d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z" />
            </svg>
        </a>
        <a href="#" class="news_messanges-item">
            <img src="{% static 'images/yt.png' %}" alt="">
        </a>
    </div>
</div>
<form method="post" action="/subscription/" class="news_form">
    <div class="news_form-title">
        Хотите быть в курсе
        последних новостей?
    </div>
    {% csrf_token %}
    <input type="email" name="mail" maxlength="254" required="" id="id_mail" class="footer_form-inp" placeholder="E-mail">
    <button class="news_form-btn">Подписаться</button>
</form>
<div class="news_wraiting">
    <div class="news_wraiting-title">
        О чём мы пишем
    </div>
    <div class="news_wraiting-text">
        {% for cat in catlist %}
        <a class="{{cat.size}}" style="color: #0e91a5;" href="/news/{{cat.slug}}/"> {{cat.name}} </a>
        {% endfor %}
    </div>
</div>
<form action="/news/{% if razItem %}{{razItem}}/{% endif %}" class="news_search">
    <div class="news_search-form">
        <input type="text" name="search_name" id="" value="{{search_name}}" class="news_search-inp" placeholder="Поиск">
        <button class="news_search-btn"></button>
    </div>
    <div class="news_search-title">
        АРХИВ НОВОСТЕЙ
    </div>
    <div class="select">
        <div class="select_header">
            <span class="select_current">Выберите месяц</span>
        </div>
        <div class="select_body">
            <a href="/news/?month=01"><div class="select_item">Январь</div></a>
            <a href="/news/?month=02"><div class="select_item">Февраль </div></a>
            <a href="/news/?month=03"><div class="select_item">Март </div></a>
            <a href="/news/?month=04"><div class="select_item">Апрель </div></a>
            <a href="/news/?month=05"><div class="select_item">Май </div></a>
            <a href="/news/?month=06"><div class="select_item">Июнь </div></a>
            <a href="/news/?month=07"><div class="select_item">Июль </div></a>
            <a href="/news/?month=08"><div class="select_item">Август </div></a>
            <a href="/news/?month=09"><div class="select_item">Сентябрь </div></a>
            <a href="/news/?month=10"><div class="select_item">Октябрь </div></a>
            <a href="/news/?month=11"><div class="select_item">Ноябрь </div></a>
            <a href="/news/?month=12"><div class="select_item">Декабрь </div></a>
        </div>
    </div>
</form>